version: '3.8'

services:
  minimal-polynomial-finder:
    build:
      context: .
      dockerfile: Dockerfile
    image: minimal-polynomial-finder:latest
    container_name: minimal-polynomial-finder
    # Remove container after execution
    restart: "no"
    # If you want to run interactively, uncomment the following:
    # stdin_open: true
    # tty: true
    # command: /bin/bash

